import type { Product } from "@/lib/models/Product";

export const ShopItems: Product[] = [
  {
    id: 1,
    slug: "sun-t-shirt",
    title: "Sun T-Shirt",
    type: "merch",
    price: 11,
    salesPrice: 11,
    onSale: false,
    description: "Oversized T-Shirt with sun emblem on back.",
    image: "/shop/merch/lala-azizli-T-r1Y3vG-7M-unsplash.jpg",
    addedDate: "2025-01-14",
    reviews: [
      {
        id: 1,
        title: "First review",
        content: "Beautiful T-Shirt. Would recommend!",
        author: { id: 1, username: "John Doe" },
        createdAt: "2026-06-25",
        rating: 4,
      },
      {
        id: 2,
        title: "Second review",
        content: "Ok look and feel, but a little small in size L.",
        author: { id: 1, username: "John Doe" },
        createdAt: "2026-06-25",
        rating: 2,
      },
    ],
  },
  {
    id: 2,
    slug: "estd-mug",
    title: "ESTd Mug",
    type: "merch",
    price: 15,
    salesPrice: 11,
    onSale: true,
    description: "ESTd coffee mug with location.",
    image: "/shop/merch/calvin-craig-bOg8cRMh6To-unsplash.jpg",
    addedDate: "2026-06-25",
    reviews: [],
  },
  {
    id: 3,
    slug: "grace-chapel-t-shirt",
    title: "Grace Chapel T-Shirt",
    type: "merch",
    price: 10,
    salesPrice: 8,
    onSale: true,
    description: "Grace Fitted T-Shirt with Eagle emblem on the back.",
    image: "/shop/merch/keagan-henman-XYtuOYfIg_M-unsplash.jpg",
    addedDate: "2026-06-25",
    reviews: [],
  },
  {
    id: 4,
    slug: "random-charity-artifact",
    title: "Random Charity Artifact",
    type: "merch",
    price: 8,
    salesPrice: 8,
    onSale: false,
    description:
      "Get a random coffee shop artifact by supporting various coffee farmers.",
    image: "/shop/merch/christina-radevich-PoG2cCucTHE-unsplash.jpg",
    addedDate: "2026-06-25",
    reviews: [],
  },
  {
    id: 5,
    slug: "brazil-250g-coffee-beans",
    title: "Brazil 250g Coffee Beans",
    type: "beans",
    price: 12,
    salesPrice: 12,
    onSale: false,
    description: "High-quality coffee beans from Brazil.",
    image: "/shop/coffee/lex-sirikiat-QouiCn7u6kw-unsplash.jpg",
    addedDate: "2026-06-25",
    reviews: [],
  },
  {
    id: 6,
    slug: "1kg-random-blend",
    title: "1kg Random Blend",
    type: "beans",
    price: 12,
    salesPrice: 10,
    onSale: true,
    description:
      "Perfectly fine, yet it did not meet our quality standards. Offered at a discounted price.",
    image: "/shop/coffee/justus-menke-83ijPo1g9og-unsplash.jpg",
    addedDate: "2026-03-23",
    reviews: [],
  },
  {
    id: 7,
    slug: "ethiopia-natural-250g-coffee-beans",
    title: "Ethiopia Natural 250g Coffee Beans",
    type: "beans",
    price: 16,
    salesPrice: 16,
    onSale: false,
    description: "Natural Ethiopian coffee beans of High Quality.",
    image: "/shop/coffee/nathan-dumlao-bx_JfZtQ-Hs-unsplash.jpg",
    addedDate: "2026-03-21",
    reviews: [],
  },
  {
    id: 8,
    slug: "espresso-glass",
    title: "Espresso Glass",
    type: "equipment",
    price: 35,
    salesPrice: 32,
    onSale: true,
    description: "4 x 6cl Espresso Glasses in thick and sturdy glassware.",
    image: "/shop/equipment/nathan-dumlao-dvuHNTJxIsg-unsplash.jpg",
    addedDate: "2026-08-03",
    reviews: [],
  },
  {
    id: 9,
    slug: "barsetto-espresso-machine",
    title: "Barsetto Espresso Machine",
    type: "equipment",
    price: 1450,
    salesPrice: 1450,
    onSale: false,
    description:
      "High-performance espresso machine by Barsetto. Maintenance service sold separately.",
    image: "/shop/equipment/qingyu-Ft1yz6M6-yQ-unsplash.jpg",
    addedDate: "2026-04-15",
    reviews: [],
  },
  {
    id: 10,
    slug: "cappuccino-mugs",
    title: "Cappuccino Mugs",
    type: "equipment",
    price: 50,
    salesPrice: 50,
    onSale: false,
    description: "2 x 2.5dl Cappuccino Mugs in thick and sturdy porcelain.",
    image: "/shop/equipment/tabitha-turner-KWZ-rg9o76A-unsplash.jpg",
    addedDate: "2026-06-20",
    reviews: [],
  },
];
